# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1024, 768))
        Form.setMaximumSize(QtCore.QSize(1024, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.tbl_main = QtWidgets.QTableWidget(Form)
        self.tbl_main.setGeometry(QtCore.QRect(10, 79, 1000, 668))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_main.sizePolicy().hasHeightForWidth())
        self.tbl_main.setSizePolicy(sizePolicy)
        self.tbl_main.setMinimumSize(QtCore.QSize(1000, 668))
        self.tbl_main.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.tbl_main.setFrameShape(QtWidgets.QFrame.Panel)
        self.tbl_main.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tbl_main.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tbl_main.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_main.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_main.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_main.setTabKeyNavigation(False)
        self.tbl_main.setProperty("showDropIndicator", False)
        self.tbl_main.setDragDropOverwriteMode(False)
        self.tbl_main.setAlternatingRowColors(True)
        self.tbl_main.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tbl_main.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_main.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_main.setCornerButtonEnabled(False)
        self.tbl_main.setRowCount(0)
        self.tbl_main.setColumnCount(0)
        self.tbl_main.setObjectName("tbl_main")
        self.tbl_main.horizontalHeader().setVisible(True)
        self.tbl_main.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_main.horizontalHeader().setDefaultSectionSize(50)
        self.tbl_main.horizontalHeader().setHighlightSections(True)
        self.tbl_main.horizontalHeader().setStretchLastSection(False)
        self.tbl_main.verticalHeader().setVisible(False)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 419, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmb_jitikai = QtWidgets.QComboBox(self.layoutWidget)
        self.cmb_jitikai.setObjectName("cmb_jitikai")
        self.horizontalLayout.addWidget(self.cmb_jitikai)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cmb_kumi = QtWidgets.QComboBox(self.layoutWidget)
        self.cmb_kumi.setObjectName("cmb_kumi")
        self.horizontalLayout.addWidget(self.cmb_kumi)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cmb_han = QtWidgets.QComboBox(self.layoutWidget)
        self.cmb_han.setObjectName("cmb_han")
        self.horizontalLayout.addWidget(self.cmb_han)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.chk_del = QtWidgets.QCheckBox(self.layoutWidget)
        self.chk_del.setObjectName("chk_del")
        self.horizontalLayout.addWidget(self.chk_del)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.txt_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_name.setObjectName("txt_name")
        self.horizontalLayout_2.addWidget(self.txt_name)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.txt_address = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_address.setObjectName("txt_address")
        self.horizontalLayout_2.addWidget(self.txt_address)
        self.btn_search = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_2.addWidget(self.btn_search)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_print = QtWidgets.QPushButton(Form)
        self.btn_print.setGeometry(QtCore.QRect(930, 50, 75, 23))
        self.btn_print.setObjectName("btn_print")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(930, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.btn_search.clicked.connect(Form.list_search)
        self.cmb_jitikai.currentTextChanged['QString'].connect(Form.jitikai_change)
        self.cmb_kumi.currentIndexChanged['QString'].connect(Form.kumi_change)
        self.tbl_main.cellDoubleClicked['int','int'].connect(Form.list_click)
        self.btn_print.clicked['bool'].connect(Form.list_print)
        self.pushButton.clicked.connect(Form.csvload_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "きじが台地区住民自治協議会"))
        self.tbl_main.setSortingEnabled(False)
        self.label_2.setText(_translate("Form", "自治会"))
        self.label_3.setText(_translate("Form", "組"))
        self.label_4.setText(_translate("Form", "班"))
        self.chk_del.setText(_translate("Form", "削除データを含む"))
        self.label_5.setText(_translate("Form", "氏名"))
        self.label_6.setText(_translate("Form", "住所"))
        self.btn_search.setText(_translate("Form", "検索"))
        self.btn_print.setText(_translate("Form", "印刷"))
        self.pushButton.setText(_translate("Form", "CSV読込"))

